swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "1.0.0"
  title: "WSO2 Identity Server Claim Verification Rest API"
  description: |
    This document specifies a **Claim Verification RESTfulAPI** for WSO2 **Identity Server** .
    It is written with [swagger 2](http://swagger.io/).
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/identity-server/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
  - https

basePath: /t/{tenant-domain}/api/identity/claim-verification/v1.0

consumes:
  - application/json
produces:
  - application/json

paths:
  # Endpoint to initiate the claim verification process.
  "/init":
    post:
      description: |
        This API is used to initiate the claim verification process. It will notify the relevant parties that a claim verification has been requested.
      parameters:
        - name: VerificationInitiatingRequest
          in: body
          description:  Request object for initiating the claim verification process.
          required: true
          schema:
            $ref: '#/definitions/VerificationInitiatingRequest'
      responses:
        200:
          description: Success response along with the confirmation code to invoke next request.
          schema:
            $ref: '#/definitions/VerificationInitiatingResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'

  # Endpoint to validate the claim value.
  "/validate":
    post:
      description: |
        This API is used to invoke the available validation mechanism to validate given claim value.
      parameters:
        - name: ValidationRequest
          in: body
          description:  Request object containing data for the validation process.
          required: true
          schema:
            $ref: '#/definitions/ValidationRequest'
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ValidationResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'

  # Endpoint to confirm the claim value.
  "/confirm":
    post:
      description: |
        This API is used to confirm the new claim value after validating it.
      parameters:
        - name: ConfirmationRequest
          in: body
          description:  Request object to finalize the process which states whether the verification was successful or not.
          required: true
          schema:
            $ref: '#/definitions/ConfirmationRequest'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'

  # Endpoint to terminate the claim verification process.
  "/revoke":
    post:
      description: |
        This API is used to terminate the verification process.
      parameters:
        - name: RevocationRequest
          in: body
          description:  Request object to terminate the verification process.
          required: true
          schema:
            $ref: '#/definitions/RevocationRequest'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  #-----------------------------------------------------
  # Validation response object
  #-----------------------------------------------------
  ValidationRequest:
    type: object
    required:
      - code
      - requireAdditionalValidation
    properties:
      code:
        description: Confirmation code related to the claim verification request.
        type: string
      requireAdditionalValidation:
        description: States whether or not to end the process from current request.
        type: boolean
      properties:
        description: Additional properties that may be needed to complete the validation.
        type: array
        items:
          $ref: '#/definitions/Property'
  #-----------------------------------------------------
  # Validation response object
  #-----------------------------------------------------
  ValidationResponse:
    type: object
    properties:
      status:
        description: Current status of the claim.
        type: string
      properties:
        description: Optional set of properties that may be sent with response. This will be used to send the new confirmation code and the username of the user when the verification process is incomplete.
        type: array
        items:
          $ref: '#/definitions/Property'
      link:
        $ref: '#/definitions/Link'

  #-----------------------------------------------------
  # Claim verification initiating request object
  #-----------------------------------------------------
  VerificationInitiatingRequest:
    type: object
    required:
      - user
      - claim
      - properties
    properties:
      user:
        $ref: '#/definitions/User'
      claim:
        $ref: '#/definitions/Claim'
      properties:
        type: array
        items:
          $ref: '#/definitions/Property'

  #-----------------------------------------------------
  # Claim verification initiating response object
  #-----------------------------------------------------
  VerificationInitiatingResponse:
    type: object
    properties:
      code:
        description: Confirmation code related to the claim verification request.
        type: string
      link:
        $ref: '#/definitions/Link'

  #-----------------------------------------------------
  # Confirmation request object
  #-----------------------------------------------------
  ConfirmationRequest:
    type: object
    required:
      - code
      - status
    properties:
      code:
        description: Confirmation code related to the claim verification request.
        type: string
      status:
        description: Verification status of the claim(SUCCESSFUL/FAILED).
        type: string

  #-----------------------------------------------------
  # Revocation request object
  #-----------------------------------------------------
  RevocationRequest:
    type: object
    required:
      - code
    properties:
      code:
        description: Confirmation code related to the claim revocation request.
        type: string

  #-----------------------------------------------------
  # The Property  object
  #-----------------------------------------------------
  Property:
    description: Property map to pass additional properties that may be required.
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  #-----------------------------------------------------
  # The User  Object
  #-----------------------------------------------------
  User:
    description: User that the claim belongs to.
    type: object
    properties:
      username:
        description: Username of the user.
        type: string
      realm:
        description: User store that the user resides in.
        type: string

  #-----------------------------------------------------
  # The Claim  Object
  #-----------------------------------------------------
  Claim:
    description: Claim that is requested for verification.
    type: object
    properties:
      claimUri:
        description: Claim uri of the claim that the value needs to be set.
        type: string
      value:
        description: Value for the claim.
        type: string

  #-----------------------------------------------------
  # Link object
  #-----------------------------------------------------
  Link:
    type: object
    properties:
      rel:
        type: string
      uri:
        type: string

  #-----------------------------------------------------
  # The Error Response  object
  #-----------------------------------------------------
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string
